Keithley2231A DC Power Supply
biqute/qinst pull request #29
Opened 2023-12-01 16:22 UTC by marcogobbo

Checklist before review:
- [x] Test on hardware.

Checklist before merge:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Documentation is updated.

2023-12-01 16:47 UTC, PietroCampana requested changes

2023-12-01 16:47 UTC, PietroCampana commented on src/qinst/serial/keithley2231a.py
> +        return self.query("INST:NSEL?")
```suggestion
    def ch_select(self) -> int:
        """Select the channel to use."""
        return int(self.query("INST:NSEL?"))
```

2023-12-01 16:47 UTC, PietroCampana commented on src/qinst/serial/keithley2231a.py
> +        )
```suggestion
    def voltage(self, value: float):
        v_max = 5 if self.ch_select == 3 else 30
        self.write(
            f"SOUR:VOLT:LEV:IMM:AMPL {self.validate_range(value, 0, vmax)}"
        )
```

2023-12-01 16:47 UTC, PietroCampana commented on src/qinst/serial/keithley2231a.py
> +        return self.query("SOUR:VOLT:LEV:IMM:AMPL?")
```suggestion
        return float(self.query("SOUR:VOLT:LEV:IMM:AMPL?"))
```

2023-12-01 16:47 UTC, PietroCampana commented on src/qinst/serial/keithley2231a.py
> +        return self.query("SOUR:CURR:LEV:IMM:AMPL?")
Remember to cast the return variable to the specified type

2023-12-01 16:47 UTC, PietroCampana commented on src/qinst/serial/keithley2231a.py
> +        self.write(f"SOUR:VOLT:LIMIT:LEV {self.validate_range(value, 0, 3)}")
delete "ch" argument from properties

2023-12-01 16:50 UTC, rodolfocarobene commented on src/qinst/serial/keithley2231a.py
> +            self.write("SYST:LOC")
For uniformity, add log.info for connection and disconection

2023-12-04 15:57 UTC, PietroCampana approved these changes

2023-12-04 15:58 UTC, merged